spring.application.name=url-shortener
server.port=9000

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Redis connection
spring.redis.host=localhost       # or 'redis' if using Docker Compose service name
spring.redis.port=6379
spring.redis.password=            # leave empty if no password
spring.redis.timeout=60000

# Optional: connection pool settings
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-idle=8
spring.redis.lettuce.pool.min-idle=0
spring.redis.lettuce.pool.max-wait=-1



# ==========================================================
# Kafka
# ==========================================================
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Consumer
spring.kafka.consumer.group-id=url-shortener-analytics
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

# Jackson JSON deserialization
spring.kafka.consumer.properties[spring.json.value.default.type]=com.url.shortener.dto.AnalyticsEvent
spring.kafka.consumer.properties[spring.json.trusted.packages]=com.url.shortener.dto

# Topic
kafka.topic.url-click-events=url-click-events


# ==========================================================
# Swagger / OpenAPI
# ==========================================================

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Expand API operations by default
springdoc.swagger-ui.doc-expansion=list

# Enable "Try it out"
springdoc.swagger-ui.try-it-out-enabled=true

# Sort operations by HTTP method
springdoc.swagger-ui.operations-sorter=method

# Sort tags alphabetically
springdoc.swagger-ui.tags-sorter=alpha
